blog/apps/user/urls.py
from django.urls import path
from . import views  

app_name = "user" 
urlpatterns = [
    path("login/", views.loginUser, name="login"),
    path("profile/<int:id>", views.profile, name="profile"),
    path("register/", views.registerUser, name="register"),
    path("logout/", views.logoutUser, name="logout"),
    path("changePassword/", views.changePassword, name="changePassword"),
    ]  

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home, name="home"), #pagina principal
    path("login/", include("apps.login.urls")), #apartado de login
    path("post/", include("apps.post.urls")), #apartado de post
    #path("crear-articulo/", include("apps.post.urls")),
    #path('home/', views.home, name="home"),
    path("about/", views.about, name="acerca"),
    path('contact/',views.contacto, name="contacto"),
    #path('categorias/', views.publicaciones, name="categorias"),
    path('crear-categoria/', views.crear_categoria, name="nueva categoria"),
    #path('detalle_publicacion/', views.detalle_publicacion, name="detalle_publicacion"),
    path('crear_post/', views.agregar_publicacion, name='crear_post'),
    path('editar_post/<int:id>/', views.editar_publicacion, name='editar_post'),
    path('eliminar_post/<int:id>/', views.eliminar_publicacion, name='eliminar_post'),
    #path('categorias/', views.mostrar_articulo, name="mostrar_articulo"),
    #path('crear_comentario/<int:post_id>/', views.crear_comentario, name='crear_comentario'),
    path('mostrar-comentario/', views.mostrar_comentarios, name="mostrar"),
]

blog/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1 class="text-info">Grupo Pythoneers</h1>
    <p>Este blog de noticias fue el proyecto final de la Etapa 2 del Informatorio</p>
    <div class="d-flex justify-content-around mt-5">
       <section class="d-flex flex-column">
        <p>El grupo Pythoneers está conformado por:</p>
        <ul>
            <li class="list-group-item my-4">Fabian Yrala</li>
            <li class="list-group-item my-4">Pedro Morinigo</li>
            <li class="list-group-item my-4">Yamila Fogar</li>
            <li class="list-group-item my-4">Daira Cuquejo</li>
            <li class="list-group-item my-4">Federico Bazan</li>
            <li class="list-group-item my-4">Gustavo Palacios</li>
        </ul>
       </section>
       <section>
        <img src="{% static '../media/src/about.png' %}" alt="about" width="300px">
       </section>
    </div>

</div>
{% endblock %}

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es-ar" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extra_styles %}{% endblock extra_styles %}
    <title>{% block title %}Pythoneers Noticias{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'logo/News_icon-icons.com_74697.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/style.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div id="content" class="bg-dark d-flex align-items-center justify-content-center container">
        {% block content %}{% endblock content %}
    </div>
    {% include "footer.html" %}
    {% block extra_js %}{% endblock extra_js %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
</body>
</html>

blog/templates/borrar_comentario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

blog/templates/category.html
{% extends 'index.html' %} 
{% block title %}Artículos{% endblock %}

{% block background %}{% load static %}{% static 'Bootstrap/img/art-bg.jpg' %}{% endblock %}

{% block headers %}
<h1 style="color: rgba(0, 0, 0, 0.699);">Artículos</h1>
<span class="subheading" style="color: rgba(0, 0, 0, 0.899);">los artículos se organizan en categorías</span>
{% endblock %}

{% block content %}
<div class="row"> 
    <div class="col-lg-3 col-md-4 offset-lg-1">
        <img class="img-fluid avatar" src="{% static 'Bootstrap/img/grupo.png' %}" alt="imagen1" title="soy un perrito">
    </div>
    <div class="col-lg-7 col-md-8">
        <h2 class="section-heading">Grupo Pythoneers</h2>   
        <br>
        <h3>Grupo creado en el 2023</h3>
        
      
        <p>Creado en... lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio.</p>
           
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit...</p>
       <button class="btn btn-success"><a href="{% url 'crear_post' %}">Crear nueva publicacion</a></button> 
     
    </div>
    <div class="col-lg-7 col-md-8">
   
         <div>
            <h6>Publicaciones realizadas: {{posteo}}</h6>
         </div>
         <div>
            <ul>
             
               {% for publicacion in publicaciones  %}
                <li>
                    <h2>{{publicacion.titulo}}</h2>
                        {{publicacion.contenido}}
                        {{publicacion.resumen}}
                    fecha: <b>{{publicacion.fecha_creacion}}</b>
                    creado por: <b>{{publicacion.autor}}</b>
                    
                    <button class="btn btn-info"><a href="/editar_post/{{ publicacion.id }}">Editar</a></button>
                    <button  class="btn btn-danger"><a href="/eliminar_post/{{ publicacion.id }}">Eliminar</a></button>
                    <div>
                        <h4>Comentarios:</h4>
                        <ul>
                            {% if comentarios %}
                            {% for comentario in comentarios %}
                                {% if comentario.post == publicacion %}
                                <li>

                                    <p><strong>{{ comentario.autor }}</strong>: {{ comentario.contenido }}</p>
                                    <p>Fecha de creación: {{ comentario.fecha_creacion }}</p>
                                </li>
                              {% endif %}
                            {% endfor %}
                            {% else %}
                            <h5>No existen comentarios</h5>

                            {% endif %}
                        </ul>
                    </div>
                    

            {% if publicacion.permitir_comentarios %}
                    <form method="post">
                    {% csrf_token %}
                        <textarea name="contenido" rows="4" cols="50" placeholder="Agrega un comentario..."></textarea>
                        <input type="hidden" name="fecha_creacion" value="{{ publicacion.fecha_creacion|date:"Y-m-d" }}">
                                   
                    <button type="submit" class="btn btn-primary">Comentar</button>
                    </form>
            {% endif %}
           
            
     
                </li>
                               
               {% endfor %}
            </ul>
           
         </div>
                 

    </div>
    
</div>
   
{% endblock%}

blog/templates/contact.html
{% extends 'index.html' %} 
{% block title %}Contacto{% endblock %}

{% block background %}{% load static %}{% static 'Bootstrap/img/contacto.jpg' %}{% endblock %}

{% block headers %}
<h1>Contacto</h1>
<span class="subheading">Contáctanos</span>
{% endblock %}

{% block content %}
<div class="row"> 
    <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque quidem nihil repellendus tempora consequuntur modi quas repudiandae ex, voluptas quod fuga odio, alias aut in atque, veniam dolor excepturi mollitia.</p>
      
        <p><b>Teléfono:</b> {{contacto}} </p>
        <p> <u>"Desarrollo web"</u> </p>
        <p><b>Horarios:</b> de 16hs a 21hs </p>
        <br>
   
    </div>
      <form>
        <img src="../staticfiles/Bootstrap/img/user2.jpg" class="img-fluid avatar" alt="usuario" style="width:150px;height:150px;">
          <div class="mb-3">
            <label for="exampleInputName1" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="exampleInputName1" aria-describedby="nameHelp" style="width:400px;">
            <div id="nameHelp" class="form-text">
            </div>
          </div>
          <label for="exampleInputEmail1" class="form-label">Email</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" style="width: 400px;">
          <div id="emailHelp" class="form-text">
            nunca compartiremos su correo electrónico con nadie más..</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Contraseña</label>
          <input type="password" class="form-control" id="exampleInputPassword1" style="width:400px;">
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Verificar</label>
        </div>
        <div class="form-floating">
            <textarea class="form-control" placeholder="dejá un comentario acá" id="floatingTextarea" style="width:400px;height:230px;"></textarea>
            <label for="floatingTextarea">Comentarios</label>
          </div><br>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
      
</div>
{% endblock %}

blog/templates/detalle_public.html
{% extends 'index.html' %} 
{% block title %}Publicaciones{% endblock %}

{% block background %}{% load static %}{% static 'Bootstrap/img/portfolio-bg.jpg' %}{% endblock %}

{% block headers %}
<h1 style="color: rgba(0, 0, 0, 0.699);">Nuevo Artículo</h1>
<span class="subheading" style="color: rgba(0, 0, 0, 0.699);">Nuestra Trayectoria</span>
{% endblock %}

{% block content %}
            
        <div class="row project">  	
            <div class="col-lg-3 col-md-4 offset-lg-1">
                <img class="img-fluid" src="#" alt="">
            </div>
            <div class="col-lg-7 col-md-8">
                <h2 class="section-heading title">{{nosotros}}</h2>   
                
                    
              
            </div>
            
           
                        
        </div>
        <div id="openModal" class="modalDialog">
            <div>
                <a href="#close" title="Close" class="close">X</a>
                <h2>Mi modal</h2>
                <p>Este es un ejemplo de modal, creado gracias al poder de CSS3.</p>
                <p>Puedes hacer un montón de cosas aquí, como alertas o incluso crear un formulario de registro aquí mismo.</p>
            </div>
        </div>
   
{% endblock %}

blog/templates/editar.html
{% extends 'index.html' %} 
{% block title %}Artículos{% endblock %}

{% block background %}{% load static %}{% static 'Bootstrap/img/art-bg.jpg' %}{% endblock %}

{% block headers %}
<h1 style="color: rgba(0, 0, 0, 0.699);">Artículos</h1>
<span class="subheading" style="color: rgba(0, 0, 0, 0.899);">los artículos se organizan en categorías</span>
{% endblock %}

{% block content %}
<div class="row"> 
    <div class="col-lg-3 col-md-4 offset-lg-1">
        <img class="img-fluid avatar" src="{% static 'Bootstrap/img/grupo.png' %}" alt="imagen1" title="soy un perrito">
    </div>
    <div class="col-lg-7 col-md-8">
        <h2 class="section-heading">Grupo Pythoneers</h2>   
        <br>
        <h3>Editar Publicación</h3>
                    
    </div>
    <div class="form-group">
   
       <form method="POST">
        <table class="table-primary">
            
         {{formPost}}
                

        </table>
        
        <button type="submit" class="btn btn-primary">Guardar</button>
        {% csrf_token %}
       </form>

    </div>
    
</div>
   
{% endblock%}

blog/templates/footer.html
<footer id="footer" class="container-fluid">
    <div class="d-flex justify-content-around align-items-center">
        <span class="text-center">&copy; 2023 Pythoneers. Todos los derechos reservados.</span>
        <div class="d-flex align-items-center">
            <span class="me-3">Nuestras redes</span>
            <div class="d-flex gap-3">
                <a href="https://www.facebook.com/" target="_blank">Facebook</a>
                <a href="https://www.instagram.com/" target="_blank">Instagram</a>
                <a href="https://www.twitter.com/" target="_blank">Twitter</a>
            </div>
        </div>
    </div>
</footer>

blog/templates/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg bg-dark d-flex" id="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'logo/pyy.png' %}" style="width: 120px;" ></a>
      {% comment %} boton del nav en mobile {% endcomment %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      {% comment %} menu del nav {% endcomment %}
      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %} ">Sobre nosotros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#destacados">Destacados</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#destacados" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categorías
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Categoría uno</a></li>
              <li><a class="dropdown-item" href="#">Categoría dos</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Todas las Categorías</a></li>
            </ul>
          </li>
        </div>
        {% comment %} ####IMPORTANTE#### {% endcomment %}
        {% if request.user.is_authenticated and request.user.userprofile.is_collaborator %}
        <button>
          crear post
        </button>
        
        {% endif %}

        {% comment %} opciones de usuario {% endcomment %}
        <div class="" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              {% if request.user.is_authenticated %}
                  <a class="nav-link disable" aria-current="page" href="{% url 'user:logout' %}">Cerrar sesión</a>
              {% else %}
                  <a class="nav-link active link-info" aria-current="page" href="{% url 'user:login' %}">Iniciar sesión</a>
              {% endif %}
            </li>
              {% if not request.user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link link-info" href="{% url 'user:register' %}">Registrarse</a>
                  </li>
              {%endif%}
              
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link link-info" href="{% url 'user:profile' request.user.id %}"> {{request.user.username|capfirst}}</a>
              </li>
              {% endif %}
          </ul>
        </div>
      </div>
        </ul>
  </nav>
</header>

blog/templates/home.html
{% extends 'index.html' %}

{% block title %}Home{% endblock %}

{% block background %}{% load static %}{% static 'Bootstrap/img/AI.jpg' %}{% endblock %}

{% block headers %}
<h1 style="color: rgb(238, 232, 232);">Bienvenidos al Sitio Web</h1>
<span class="subheading">Hablamos de Inteligencia Articial</span>

{% endblock %}
{% block content %}
<h2>Una pequeña ciudad llamada Cognópolis</h2>
<p>Había una vez una pequeña ciudad llamada Cognópolis, donde la inteligencia artificial (IA) había dejado de ser solo un concepto futurista para convertirse en una herramienta cotidiana y valiosa para sus habitantes. En Cognópolis, la IA estaba integrada en cada aspecto de la vida diaria, desde el transporte hasta la atención médica y la educación.</p>
<br>
<p>Un día, Lucas, un joven apasionado por la tecnología, llegó a la ciudad en busca de oportunidades para realizar su sueño de ser inventor. Al explorar las calles, se maravilló al ver la forma en que la IA estaba en todas partes, mejorando la eficiencia y la calidad de vida de sus habitantes. Decidió que quería aprender más sobre esta fascinante tecnología y se matriculó en la Universidad de Cognópolis, famosa por sus programas de IA.</p>
<br>
<p>En la universidad, Lucas se sumergió en el mundo de la inteligencia artificial, aprendiendo cómo las máquinas podían analizar grandes cantidades de datos para tomar decisiones informadas y predecir situaciones futuras. Descubrió cómo la IA impulsaba avances en áreas como la medicina, donde los diagnósticos y tratamientos eran más precisos y personalizados, y en la ecología, donde ayudaba a proteger el medio ambiente.</p>
<br>
<p>Un día, mientras participaba en un proyecto de investigación sobre energías renovables, Lucas encontró un antiguo molino de viento abandonado en las afueras de la ciudad. Comenzó a preguntarse si podría revivir esa tecnología con la ayuda de la IA. Entonces, se dedicó en cuerpo y alma a convertir el molino en una fuente de energía limpia y sostenible.</p>
<br>
<p>Con el apoyo de sus profesores y compañeros, Lucas diseñó un sistema inteligente que ajustaba la posición de las aspas del molino en función de los datos climáticos y la demanda de energía. La IA también permitía detectar fallos y realizar mantenimiento preventivo, garantizando el óptimo funcionamiento del molino en todo momento.</p>
<br>
<p>La noticia de su proyecto se difundió rápidamente por la ciudad, y pronto el molino de viento se convirtió en un símbolo del poder transformador de la inteligencia artificial. La gente comenzó a comprender aún más la importancia de utilizar herramientas de IA en la resolución de problemas, no solo en términos de eficiencia, sino también en la contribución a un mundo más sostenible y consciente.</p>
<br>
<p>La historia de Lucas y su molino de viento inspiró a otros jóvenes de Cognópolis a embarcarse en carreras en tecnología e inteligencia artificial. Con el tiempo, la ciudad se convirtió en un centro de innovación y desarrollo de IA, atrayendo a talentos de todo el mundo.</p>
<br>
<p>Y así, gracias al ingenio y la pasión de Lucas, Cognópolis demostró que la inteligencia artificial no era solo una herramienta, sino una aliada poderosa para la creación de un futuro mejor. Al integrar la IA en sus vidas, los ciudadanos aprendieron que, con un enfoque ético y responsable, podían lograr avances extraordinarios que beneficiaban a toda la humanidad. La inteligencia artificial se convirtió en un faro de esperanza, iluminando el camino hacia un mundo más inteligente y sostenible para todos.</p>
{% endblock %}

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>{% block title %}{% endblock %} | Blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'Bootstrap/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="{% static 'Bootstrap/css/clean-blog.min.css' %}" rel="stylesheet">
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">BLOG </a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <!-- Menú -->
            <i class="fa fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post:publicaciones' %}">Publicaciones</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'acerca' %}">Acerca de</a>
              </li>
             
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Registrarme</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Iniciar Sesión</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
   
    <!-- Cabecera -->
    <header class="masthead" style="background-image: url('{% block background %}{% endblock %}')">
        <div class="overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <div class="site-heading">
                {% block headers %}<img src="../staticfiles/Bootstrap/img/AI.jpg" class="overlay" alt="ai" class="masthead">{% endblock %}
              </div>
            </div>
          </div>
        </div>
      </header>
      
       <!-- Contenido -->
       <div class="container">
        {% block content %}{% endblock %}
      </div>
      
      {% if request.path != "/" %} {% endif %}
     
    <br>
     <!-- Pié de página -->
    <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <ul class="list-inline text-center">
                <li class="list-inline-item">
                  <a href="https://twitter.com" target="_blank">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="https://github.com" target="_blank">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="https://www.youtube.com" target="_blank">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
              </ul>
              <p class="copyright text-muted">Copyright &copy; 2023 Sitio web Hecho por Grupo Pythoneers 🍻</p>
            </div>
          </div>
        </div>
      </footer>
 
   
    <!-- Bootstrap y Javascripts -->
    <script src="{% static 'Bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'Bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'Bootstrap/js/clean-blog.min.js' %}"></script>

</body>
</html>

blog/templates/nueva_publicacion.html
{% extends 'index.html' %} 
{% block title %}Artículos{% endblock %}

{% block background %}{% load static %}{% static 'Bootstrap/img/art-bg.jpg' %}{% endblock %}

{% block headers %}
<h1 style="color: rgba(0, 0, 0, 0.699);">Artículos</h1>
<span class="subheading" style="color: rgba(0, 0, 0, 0.899);">los artículos se organizan en categorías</span>
{% endblock %}

{% block content %}
<div class="row"> 
    <div class="col-lg-3 col-md-4 offset-lg-1">
        <img class="img-fluid avatar" src="{% static 'Bootstrap/img/grupo.png' %}" alt="imagen1" title="soy un perrito">
    </div>
    <div class="col-lg-7 col-md-8">
        <h2 class="section-heading">Grupo Pythoneers</h2>   
        <br>
        <h3>Agregar Publicación</h3>
                    
    </div>
    <div class="form-group">
   
       <form method="POST">
        <table class="table-primary">
            
            {{formPost}}
                

        </table>
        
        <button type="submit" class="btn btn-primary">Enviar</button>
        {% csrf_token %}
       </form>

    </div>
    
</div>
   
{% endblock%}